### ISSUE TITLE
Would you tell me where I can find the causal_construction_easyuse.py？

### ISSUE THREAD

**Issue by fxx765** [lixiang-222/CausalMed#1]

**Comment by lixiang-222** [comment]
Thank you for your reminder! We previously only uploaded part of the code due to copyright issues. Now that the work has been accepted, we have uploaded the full code and preprocessed data, so you can experiment directly. At the same time, because some of the raw data is too large to upload, you need to go to the MIMIC official website to download it. If you have any other questions, please feel free to contact us. Thank you for your support and recognition of our work.
